# Generated by Django 3.2.20 on 2023-07-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vneshnij_identifikator_dlja_importa', models.CharField(max_length=255, verbose_name='город')),
                ('familija', models.CharField(max_length=255, verbose_name='фамилия')),
                ('imja', models.TextField(max_length=255, verbose_name='имя')),
                ('otchestvo', models.TextField(max_length=255, verbose_name='отчество')),
                ('otdel', models.TextField(max_length=255, verbose_name='отдел')),
                ('dolzhnost', models.TextField(max_length=255, verbose_name='должность')),
                ('adres_elektronnoj_pochty', models.TextField(default=None, max_length=255, null=True, verbose_name='адрес электронной почты')),
                ('mobilnyj_telefon', models.TextField(default=None, max_length=255, null=True, verbose_name='мобильный телефон')),
                ('gorodskoj_telefon', models.TextField(default=None, max_length=255, null=True, verbose_name='городской телефон')),
                ('vnutrennij_telefon', models.TextField(max_length=255, verbose_name='внутренний телефон')),
                ('domashnij_telefon', models.TextField(default=None, max_length=255, null=True, verbose_name='домашний телефон')),
                ('login', models.TextField(default=None, max_length=255, null=True, verbose_name='логин')),
                ('parol', models.TextField(default=None, max_length=255, null=True, verbose_name='пароль')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
